---

- hosts: nodes
  become: yes
  become_user: root
  remote_user: vagrant

  tasks:
    - name: Create directory for ssh-keys
      file: state=directory mode=0700 dest=/root/.ssh/

    - name: Adding rsa-key in /root/.ssh/authorized_key
      copy: src=~/.ssh/id_rsa.pub dest=/root/.ssh/authorized_key owner=root mode=0600
      ignore_errors: yes

    - name: Cheking DNS
      command: host -t A google.com

    - name: Installing tools
      apt: >
        package={{ item }}
        state=present
        update_cache=yes
      with_items:
        - git
        - curl

    - name: Install Docker
      shell: curl -fsSL get.docker.com -o get-docker.sh && chmod +x get-docker.sh && ./get-docker.sh

    - name: Add the current user to docker group
      user: name=vagrant append=yes groups=docker
