---
- hosts: master
  become: true
  tasks:
    - name: Init Cluaster
      ansible.builtin.shell: kubeadm init --pod-network-cidr=192.168.0.0/16

    - name: mkdir .kube
      become: yes
      become_user: ubuntu
      ansible.builtin.file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: Copy admin.conf
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu

    - name: Get Join Command
      ansible.builtin.shell: kubeadm token create --print-join-command
      register: join_cmd_raw

    - name: Set Join Command
      set_fact:
        join_command: "{{ join_cmd_raw.stdout_lines[0] }}"

- hosts: worker
  become: true
  tasks:
    - name: Join Cluster
      ansible.builtin.shell: "{{ hostvars['master-01'].join_command }}"

- hosts: master
  vars:
    files:
        - deploys.yml
        - services.yml
        - network-policy.yml
  tasks:
    - name: Kubectl Autocomplete
      ansible.builtin.shell: echo "source <(kubectl completion bash)" >> ~/.bashrc

    - name: Install Calico
      ansible.builtin.shell: kubectl create -f https://docs.projectcalico.org/v3.23/manifests/calico.yaml

    - name: Pause 30s. Wait for cluster startup
      ansible.builtin.pause:
        seconds: 30

    - name: Copy Deploy file
      ansible.builtin.copy:
        src: "./files/{{ item }}"
        dest: "{{ item }}"
      loop: "{{ files }}"

    - name: Create Namespace app
      ansible.builtin.shell: kubectl create ns app

    - name: Apply yaml
      ansible.builtin.shell: kubectl apply -f .
