---
# Избавляемся от ошибки на центах 8: Error: Failed to download metadata for repo ‘appstream’: Cannot prepare internal mirrorlist: No URLs in mirrorlist
- name: Fix everywhere yum
  hosts: all
  tasks:
    - name: Copy script
      become: true
      ansible.builtin.script:
        cmd: ./scr/fix_yum.sh

# Установка Clickhouse
- name: Install clickhouse
  hosts: clickhouse
  roles:
    - role: clickhouse_role

# Установка Vector
- name: Install vector
  hosts: vector
  roles:
    - role: vector_role

# Установка Lighthouse
- name: Install lighthouse
  hosts: lighthouse
  handlers:
    - name: Start nginx service
      become: true
      ansible.builtin.service:
        name: nginx
        state: restarted
  pre_tasks:
    - name: Install epel-release
      become: true
      yum:
        name: epel-release
        state: present
    - name: Install Nginx
      become: true
      yum:
        name: nginx
        state: present
      notify: Start nginx service
    - name: Create Nginx config
      become: true
      template:
        src: nginx.j2
        dest: /etc/nginx/nginx.conf
        mode: 0644
      notify: Start nginx service
  roles:
    - role: lighthouse_role
  post_tasks:
    - name: Show connect URL lighthouse
      debug:
        msg: "http://{{ ansible_host }}/#http://{{ hostvars['clickhouse-01'].ansible_host }}:8123/?user={{ clickhouse_user }}"