---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myfirstpvc
  labels:
    app: main
  namespace: default
spec:
  storageClassName: ''
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  labels:
    app: main
  namespace: default
spec:
  storageClassName: ''
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /opt/share
  persistentVolumeReclaimPolicy: Delete
