---
apiVersion: v1
kind: Service
metadata:
  name: my-external-svc
  namespace: default
spec:
  ports:
    - name: nginx-http
      port: 9001
      targetPort: 80
      protocol: TCP
      nodePort: 30080
  selector:
    app: main
  type: NodePort
