---
- hosts: master
  become: true
  tasks:
    - name: Init Cluaster
      ansible.builtin.shell: kubeadm init --pod-network-cidr=10.100.0.0/16

    - name: mkdir .kube
      become: yes
      become_user: ubuntu
      ansible.builtin.file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: Copy admin.conf
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu

    - name: Get Join Command
      ansible.builtin.shell: kubeadm token create --print-join-command
      register: join_cmd_raw

    - name: Set Join Command
      set_fact:
        join_command: "{{ join_cmd_raw.stdout_lines[0] }}"

- hosts: worker
  become: true
  tasks:
    - name: Join Cluster
      ansible.builtin.shell: "{{ hostvars['master-01'].join_command }}"

- hosts: master
  tasks:
    - name: Install Flannel Plugin
      ansible.builtin.shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
