version: '2.1'

networks:
  mynet:
    driver: bridge

volumes:
  pg_data: {}
  pg_backup: {}

services:

  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_USER: netology
      POSTGRES_PASSWORD: passwd
    volumes:
      - pg_data:/var/lib/postgresql/data
      - pg_backup:/backup
      - ./request:/request
    networks:
      - mynet

  adminer:
    image: adminer
    restart: always
    networks:
      - mynet
    ports:
      - 8080:8080
