apiVersion: v1
kind: Pod
metadata:
  name: netology-web
  namespace: default
  labels:
    app: netology
spec:
  containers:
    - name: netology-web
      image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
#      ports:
#        - name: web-http
#          containerPort: 8080
#          protocol: TCP
#        - name: web-https
#          containerPort: 8443
#          protocol: TCP