apiVersion: v1
kind: Service
metadata:
  name: netology-svc
  namespace: default
spec:
  ports:
    - name: web-http
      port: 8080
    - name: web-https
      port: 8443
  selector:
    app: netology
