---
apps:
  replicaCount: 1
  multitool:
    name: multitool
    image:
      repository: wbitt/network-multitool
      pullPolicy: IfNotPresent
      tag: latest
      env:
        HTTP_PORT:  8080
        HTTPS_PORT: 8443
  nginx:
    name: nginx
    image:
      repository: nginx
      pullPolicy: IfNotPresent
      tag: 1.24
    containerPort: 80

service:
  name: my-svc
  type: ClusterIP
  port: 80
